---
title: "IDI_1"
author: "Kelsey Walker"
date: "1/30/2022"
output: html_document
---

```{r include = FALSE}
library("dplyr")
library("tidyverse")
library("readxl")
library("lubridate")
library("ggplot2")
library("fitdistrplus")
```

# Read in daily data
```{r}
data_daily <- readRDS("~kelseywalker/Desktop/EPIC HOMES/R_thesis/omni_daily_processed.rds") 

```
 

# Parameters
Results:
Min, Max, Mean, 5th & 95th percentile
```{r}

# Temperature
T_lcl <- 18 #lower comfort limit (deg C)
T_ucl <- 24 #upper comfort limit (deg C)
T_opt <- 21 #optimal temp (deg C)

# Relative Humidity
RH_lcl <- 37.5 #lower comfort limit (%)
RH_ucl <- 52.5 #upper comfort limit (%)
RH_opt <- 45 #optimal RH (%)

```

# Boundary Conditions
```{r}
inputs <- data_daily %>%
  
# Temperature
  #1. If Obs < T_lcl
  mutate(temp = replace (temp, temp < 15, T_lcl)) %>% #note that 16 is not T_lcl
  # 2. If Obs > T_ucl
  mutate(temp = replace(temp, temp > 27, T_ucl)) %>% #note that 28 is not T_ucl

# Relative Humidity
  #1. If Obs < T_lcl
  mutate(humid = replace (humid, humid < 30, RH_ucl)) %>%
  # 2. If Obs > T_ucl
  mutate(humid = replace(humid, humid > 60, RH_lcl)) 
```

# IDI Index 
```{r}
index <- inputs %>%
  mutate( temp_level1 = 10 * ((abs(T_opt - temp))/(T_ucl - T_lcl)) ) %>%
  mutate( humid_level1 = 10 * ((abs(RH_opt - humid))/(RH_ucl - RH_lcl)) ) %>%
  mutate( IDI = 1/2 * (temp_level1 + humid_level1) )

IDI <- dplyr::select(index, id_home, date, IDI)
#write_rds(IDI, "IDI.rds")
```

# Boxplots
```{r}
sample_size = index %>%
  group_by(id_home) %>%
  summarize(num = n())

box_plot <- merge(index, sample_size, by = "id_home") %>%
  mutate(myaxis = paste0(id_home, "\n", num ))


ggplot(box_plot, aes(x=myaxis , y = IDI)) +
  geom_boxplot()+
  ggtitle("IDI Boxplots") + 
  labs(x = "House ID", "\n", "sample size") +
  theme(axis.text.x = element_text(angle = 0, hjust =1))
  


```

# Facet


```{r}

ggplot(data = IDI, aes(date, IDI)) + 
  geom_point(size = 0.3) +
  facet_wrap(~id_home) +
  scale_x_date(date_labels = "%b %y") +
  theme(axis.text.x = element_text(angle = 45, hjust =1))

```


# Home examples over time
```{r}
home3 <- filter(index, id_home == "002" | id_home == "006" | id_home == "013")

ggplot(data = home3, aes(x = date)) + 
   geom_point(shape = 3, size = 1, aes(date, temp_level1, color = "red")) + 
  geom_point(shape = 4, size = 1, aes(date, humid_level1, color = "purple", shape = 4)) + 
   geom_point(aes(date, IDI, color = "black"),shape = 16, size = 1.5) +
    theme(legend.title = element_blank(), legend.position = "bottom") +
  ggtitle("Indoor Discomfort Index")  + 
  facet_grid(rows = vars(id_home)) + 
  scale_x_date(date_labels = "%b %Y") +
  scale_color_identity(
    breaks = c("black", "red", "purple"),
    labels = c("IDI", "T", "RH"),
    guide = "legend")  +
  labs(y = "IDI")

```