---
title: "IEI_1"
author: "Kelsey Walker"
date: "2/11/2022"
output: html_document
---
```{r include = FALSE}
library("dplyr")
library("tidyverse")
library("readxl")
library("lubridate")
library("ggplot2")
library("fitdistrplus")
library("gridExtra")
```

# Read in data
```{r}
IAPI_data <- readRDS("~kelseywalker/Desktop/EPIC HOMES/R_thesis/IAPI_1.rds") 
IDI_data <- readRDS("~kelseywalker/Desktop/EPIC HOMES/R_thesis/IDI.rds") 

```

```{r}
results <- inner_join(IAPI_data, IDI_data, by = c("id_home", "date")) %>%
  mutate( IEI = (IAPI + IDI)/2) %>%
  mutate(IAPI_percent = IAPI/ (IAPI + IDI) *100) %>%
  mutate(IDI_percent = IDI/(IAPI + IDI) *100)

IEI <- dplyr::select(results, id_home, date, IAPI, IDI, IEI)
write_csv(IEI, "IEI.csv")
#write_rds(IEI, "IEI.rds")
```

#Summary Table
```{r}

summary <- results 
  


```

#Box Plot
```{r}
sample_size = IEI %>%
  group_by(id_home) %>%
  summarize(num = n())

box_plot <- merge(IEI, sample_size, by = "id_home") %>%
  mutate(myaxis = paste0(id_home, "\n", num ))


ggplot(box_plot, aes(x=myaxis , y = IEI)) +
  geom_boxplot()+
  ggtitle("IEI Boxplots") + 
  labs(x = "House ID", "\n", "sample size") +
  theme(axis.text.x = element_text(angle = 0, hjust =1))
```

#Plot using facet_wrap

```{r}

ggplot(data = IEI, aes(date, IEI)) + 
  geom_point(size = 0.3) +
  facet_wrap(~id_home) +
  scale_x_date(date_labels = "%b %y") +
  theme(axis.text.x = element_text(angle = 45, hjust =1))


```



#Plot manually each home
```{r}
home3 <- filter(results, id_home == "002" | id_home == "006" | id_home == "013")


ggplot(data = home3, aes(date, IAPI)) + 
  geom_point(shape = 3, size = 1, aes(date, IAPI, color = "red")) + 
  geom_point(shape = 4, size = 1, aes(date, IDI, color = "purple", shape = 4)) + 
   geom_point(aes(date, IEI, color = "black"),shape = 16, size = 1.5) +
    theme(legend.title = element_blank(), legend.position = "bottom") +
  ggtitle("Indoor Environmental Index")  + 
  facet_grid(rows = vars(id_home)) + 
  scale_x_date(date_labels = "%b %Y") +
  scale_color_identity(
    breaks = c("black", "red", "purple"),
    labels = c("IEI", "IAPI", "IDI"),
    guide = "legend")  +
  labs(y = "IEI")
  
  #geom_point(shape = 3, color = "purple", aes(date, IAPI)) + 
  #geom_point(shape = 4, color = "red", aes(date, IDI)) +
  #scale_x_date(date_labels = "%b %Y") + #Set x-axis lable
  #scale_color_manual(breaks = c('IEI', 'IAPI', 'IDI')) + 
  #theme(axis.text.x = element_text(angle = 45, hjust =1)) +
  #theme(legend.position = "bottom")
  
```


```{r}
ggplot(data = home3, aes(date, IAPI)) + 
  geom_point(size = 1, aes(date, IAPI, color = "red"), shape =4) + 
  geom_point(size = 1, aes(date, IDI, color = "purple"), shape = 3) + 
  geom_point(aes(date, IEI, color = "black"), size = 1.5, shape = 16) +
  facet_grid(rows = vars(id_home)) +
  theme(legend.title = element_blank())+
  scale_x_date(date_labels = "%b %Y") 
  


```



```{r}


p003 <- ggplot(data = home3, aes(date, IEI)) + 
  geom_line() +
  geom_point(color = "purple", aes(date, IAPI, color = "IAPI")) + 
  geom_point(aes(date, IDI, color = "IDI")) + 
  ggtitle("Home 003")  + 
  scale_x_date(date_labels = "%b %Y") +
  theme(axis.text.x = element_text(angle = 45, hjust =1)) +
  labs(colour = "IEQ estimation") #Title Legend

home18 <- filter(results, id_home == "018")

p018 <- ggplot(data = home18, aes(date, IEI)) + 
  geom_line() +
  geom_point(color = "purple", aes(date, IAPI, color = "IAPI")) + 
  geom_point(aes(date, IDI, color = "IDI")) + 
  ggtitle("Home 018")  + 
  scale_x_date(date_labels = "%b %Y") +
  theme(axis.text.x = element_text(angle = 45, hjust =1), legend.position = "none") +
  labs(colour = "IEQ estimation") #Title Legend

grid.arrange(p003, p018,nrow = 1)

```

```{r}

ggplot(results, aes(x = date, y = id_home, fill = results$IEI)) + 
  geom_tile( colour = "white") +
  scale_fill_distiller(name = "IEI", limit = c(0,10), direction = 1) +
  ylab("Home ID") +
  ggtitle("Time Series Heatmap: IEI ") +
  scale_x_date(date_labels = "%b %Y") + #makes x-axis labels month and year
  theme_bw() #makes background white and black
```