---
title: "Sense_1"
author: "Kelsey Walker"
date: "2/6/2022"
output: html_document
---

# Librarys
```{r include = FALSE}
library("dplyr")
library("tidyverse")
library("readxl")
library("lubridate")
library("ggplot2")
library("fitdistrplus")
```

# Read in Data
```{r}
sense <- readRDS("~kelseywalker/Desktop/EPIC HOMES/R_thesis/sense_hourly.rds") %>%
  dplyr::select(!c(year, month, day)) %>%
  relocate(datetime, .before = hod) %>%
  mutate(date = date(datetime)) %>%
  relocate(date, .after = datetime)
  
# unique(sense$device_type)
```

# Charactegorize data by energy use activities: cooking, cleaning, people
```{r}
data_char <- dplyr::select(sense, id_home, datetime, date, device_type) #%>% #select columns of interest

# Cooking
cooking <- filter(data_char, device_type == 'oven'| device_type == 'microwave' |   
                    device_type == 'stove top' | device_type == 'coffee maker' | 
                    device_type == 'tea kettle' | device_type == 'toaster oven')

cooking_hr <- dplyr::select(cooking, c("id_home", "datetime") ) %>%
  distinct(id_home, datetime, .keep_all = TRUE) %>% #only keep rows of unique id_home and datetime combo
  mutate(date = date(datetime)) %>%
  group_by(id_home, date) %>%
  count(date) %>%
  rename(cooking_hr = n)

# Cleaning
cleaning <- filter(data_char, device_type == 'disposal' | device_type == 'washer' | 
                     device_type == 'dryer' | device_type == 'vacuum')
cleaning_hr <- dplyr::select(cleaning, c("id_home", "datetime") ) %>%
  distinct(id_home, datetime, .keep_all = TRUE) %>% #only keep rows of unique id_home and datetime combo
  mutate(date = date(datetime)) %>%
  group_by(id_home, date) %>%
  count(date) %>%
  rename(cleaning_hr = n)

# People
people <- filter(data_char, device_type == 'tv' | device_type == 'light' | device_type =='tv/monitor')
people_hr <- dplyr::select(people, c("id_home", "datetime") ) %>%
  distinct(id_home, datetime, .keep_all = TRUE) %>% #only keep rows of unique id_home and datetime combo
  mutate(date = date(datetime)) %>%
  group_by(id_home, date) %>%
  count(date) %>%
  rename(people_hr = n)

# ALL (ALL days of data that have energy use, some will include days/hours not recorded in the three categories above)
all <- data_char %>%
  distinct(id_home, datetime, .keep_all = TRUE) %>%
  mutate(date = date(datetime)) %>%
  group_by(id_home, date) %>%
  count(date) %>%
  rename(other_hr = n)

```

# Create dataframe of activities
```{r}
summary <- full_join(cooking_hr, cleaning_hr, by = c("id_home", "date")) %>%
  full_join(people_hr, by = c("id_home", "date")) %>%
  full_join(all, by = c("id_home", "date")) %>%
  dplyr::select(!c(other_hr))
summary[is.na(summary)] <- 0 #replace NA with 0

#write_rds(summary, "energy_activity_hour.rds")
```




# Data Characterization
#```{r}
# Hourly energy use for each house
data_agg_hr <- data %>%
  group_by(id_home, datetime) %>%
  summarise(sum(avg_wattage)) %>%
  #rename(avg_watt = 'sum(avg_wattage)') %>%
  drop_na('sum(avg_wattage)')

#Total house use - need to divide by number of days of sense recordings
data_agg_house <- data %>%
  group_by(id_home) %>%
  summarise(sum(avg_wattage)) %>%
  rename(avg_watt = 'sum(avg_wattage)')
  
#```

# Plots
#```{r}
ggplot(data_agg_hr, aes(datetime, 'sum(avg_watt)')) +
  geom_line()
#```

## House 001
#```{r}
data_001 <- filter(data, id_home == '001')
  #ggplot(data_001_agg, aes(datetime, 'sum(avg_wattage)')) +
           #geom_line()
data_c1 <- filter(data_001, sense_device_name == 'vacuum')
unique(data_001$sense_device_name)
 write_csv(data_001, "sense_001.csv")
#```

